version : "3.9"
services:
  ocr:
    image: localhost:5000/ocr-service
    restart: always
    build:
      context: .
      dockerfile: ./ocr-service/Dockerfile
    depends_on:
      - postgresql
    ports:
      - "8888:8888"
    deploy:
      mode: replicated
      replicas: 1
  postgresql:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql:/var/lib/postgresql/data"
      - "/init:/docker-entrypoint-initdb.d"
    deploy:
      mode: replicated
      replicas: 1
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    deploy:
      mode: replicated
      replicas: 1
